<script setup>
import { ref, computed, onMounted } from "vue";
import { useRouter } from "vue-router";
import { supabase } from "../lib/supabaseClient";
import CustomerNav from "../components/customer/CustomerNav.vue";
import LocationMap from "../components/maps/LocationMap.vue";
const router=useRouter(); const points=ref([]); const selected=ref(null); const loading=ref(true); const errorText=ref(""); const search=ref(""); const department=ref("Todos");
const departments=["Todos","Ahuachapán","Cabañas","Chalatenango","Cuscatlán","La Libertad","La Paz","La Unión","Morazán","San Miguel","San Salvador","San Vicente","Santa Ana","Sonsonate","Usulután"];
const filtered=computed(()=>{const q=search.value.toLowerCase().trim();return points.value.filter(p=>(department.value==="Todos"||p.department===department.value)&&(!q||[p.businessName,p.locationName,p.address,p.district,p.department].join(" ").toLowerCase().includes(q)));});
function initials(name){return String(name||"TH").trim().split(/\s+/).slice(0,2).map(w=>w[0]?.toUpperCase()).join("");}
function select(point){selected.value=point;}
async function load(){loading.value=true;errorText.value="";try{const{data,error}=await supabase.rpc("get_business_map_points");if(error)throw error;points.value=(data||[]).map(r=>({id:r.location_id,entrepreneurId:r.entrepreneur_id,name:r.location_name,locationName:r.location_name,address:r.address,latitude:Number(r.latitude),longitude:Number(r.longitude),isPrimary:Boolean(r.is_primary),businessName:r.business_name,department:r.department||"",district:r.district||"",logoUrl:r.logo_url||"",averageRating:Number(r.average_rating)||0,reviewCount:Number(r.review_count)||0}));selected.value=points.value[0]||null;}catch(e){console.error(e);errorText.value="No pudimos cargar el mapa.";}finally{loading.value=false;}}
onMounted(load);
</script>
<template>
<div class="min-h-screen bg-[#F8FBFC] pb-[78px] text-gray-700 lg:pb-10">
<header class="sticky top-0 z-40 bg-[#F8FBFC]/95 backdrop-blur-xl"><div class="mx-auto max-w-[1450px] px-3 py-4 sm:px-5 lg:px-8"><div class="grid gap-3 lg:grid-cols-[1fr_auto]"><div class="rounded-[24px] bg-white p-4 shadow-sm ring-1 ring-[#CAF0F8]"><p class="text-xs font-black uppercase tracking-[.16em] text-[#00B4D8]">Cerca de ti</p><h1 class="mt-1 text-2xl font-black text-gray-800">Mapa de emprendimientos</h1><div class="mt-3 flex items-center gap-3 rounded-[16px] bg-[#F8FBFC] px-4 py-3"><svg class="h-5 w-5 text-[#00B4D8]" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg><input v-model="search" class="w-full bg-transparent text-sm outline-none" placeholder="Buscar emprendimiento o local"></div></div><div class="lg:min-w-[760px] lg:self-end"><CustomerNav active="map" /></div></div><div class="mt-3 flex gap-2 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><button v-for="item in departments" :key="item" class="whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold" :class="department===item?'bg-[#0077B6] text-white':'bg-white text-[#0077B6] ring-1 ring-[#CAF0F8]'" @click="department=item">{{ item }}</button></div></div></header>
<main class="mx-auto max-w-[1450px] px-3 py-5 sm:px-5 lg:px-8"><div v-if="loading" class="py-24 text-center"><div class="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-[#CAF0F8] border-t-[#00B4D8]"></div></div><div v-else-if="errorText" class="rounded-[24px] bg-white p-10 text-center">{{ errorText }}</div><div v-else class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><section class="overflow-hidden rounded-[28px] bg-white p-2 shadow-sm ring-1 ring-[#CAF0F8]"><LocationMap :locations="filtered" height="min(70vh, 720px)" @select="select" /></section><aside class="lg:sticky lg:top-[175px] lg:self-start"><article v-if="selected" class="rounded-[28px] bg-white p-5 shadow-sm ring-1 ring-[#CAF0F8]"><div class="flex items-center gap-4"><img v-if="selected.logoUrl" :src="selected.logoUrl" class="h-16 w-16 rounded-[20px] object-cover"><div v-else class="flex h-16 w-16 items-center justify-center rounded-[20px] bg-[#EAF9FC] font-black text-[#0077B6]">{{ initials(selected.businessName) }}</div><div><p class="text-xs font-black uppercase tracking-[.14em] text-[#00B4D8]">{{ selected.isPrimary ? 'Local principal' : 'Sucursal' }}</p><h2 class="mt-1 text-xl font-black text-gray-800">{{ selected.businessName }}</h2><p class="mt-1 text-xs font-bold text-amber-500">★ {{ selected.averageRating.toFixed(1) }} <span class="font-semibold text-gray-400">· {{ selected.reviewCount }} reseñas</span></p></div></div><div class="mt-5 rounded-[18px] bg-[#F8FBFC] p-4"><p class="font-black text-gray-700">{{ selected.locationName }}</p><p class="mt-1 text-sm leading-6 text-gray-500">{{ selected.address }}</p></div><button class="mt-5 w-full rounded-[16px] bg-[#00B4D8] px-5 py-3.5 font-black text-white" @click="router.push({name:'Business',params:{id:selected.entrepreneurId}})">Ver perfil del emprendimiento</button></article><div v-else class="rounded-[24px] bg-white p-6 text-sm text-gray-500 shadow-sm">Selecciona un punto del mapa para ver el emprendimiento.</div></aside></div></main>
</div>
</template>
