<script setup>
// Directorio de emprendimientos. Da prioridad al negocio y deja una pequeña muestra real de sus productos.
import { ref,computed,onMounted } from "vue";
import { useRouter } from "vue-router";
import { supabase } from "../lib/supabaseClient";
import CustomerHeader from "../components/customer/CustomerHeader.vue";
const router=useRouter();
const businesses=ref([]),loading=ref(true),errorText=ref(""),search=ref(""),department=ref("Todos"),followed=ref([]),followLoading=ref([]);
const filtered=computed(()=>{const q=search.value.toLowerCase().trim();return businesses.value.filter(b=>(department.value==="Todos"||b.department===department.value)&&(!q||[b.businessName,b.description,b.department,b.district,...b.tags,...b.products.map(p=>p.name)].join(" ").toLowerCase().includes(q)));});
const featured=computed(()=>filtered.value.filter(b=>b.reviewCount>0).slice().sort((a,b)=>b.featureScore-a.featureScore||b.reviewCount-a.reviewCount).slice(0,6));
function initials(name){return String(name||"TH").trim().split(/\s+/).slice(0,2).map(w=>w[0]?.toUpperCase()).join("");}
function money(value){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(value)||0);}
function salePrice(product){const d=Math.min(90,Math.max(0,Number(product?.discountPercent)||0));return Number(product?.price||0)*(1-d/100);}
function open(id){router.push({name:"Business",params:{id}});}
function openProduct(id){router.push({name:"Product",params:{id}});}
function isFollowing(id){return followed.value.includes(id);}
function busy(id){return followLoading.value.includes(id);}
function tagClass(tag){const v=String(tag||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();if(v.includes("efectivo"))return "border-emerald-200 bg-emerald-50 text-emerald-700";if(v.includes("tarjeta"))return "border-indigo-200 bg-indigo-50 text-indigo-700";if(v.includes("transfer"))return "border-sky-200 bg-sky-50 text-sky-700";if(v.includes("retiro"))return "border-amber-200 bg-amber-50 text-amber-700";if(v.includes("domicilio")||v.includes("entrega"))return "border-orange-200 bg-orange-50 text-orange-700";if(v.includes("envio"))return "border-violet-200 bg-violet-50 text-violet-700";if(v.includes("personal"))return "border-rose-200 bg-rose-50 text-rose-700";if(v.includes("sin local"))return "border-slate-200 bg-slate-50 text-slate-600";return "border-[#90E0EF] bg-[#EAF9FC] text-[#0077B6]";}
async function loadFollows(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from("follows").select("entrepreneur_id").eq("follower_id",user.id);followed.value=(data||[]).map(r=>r.entrepreneur_id);}
async function toggleFollow(id){if(busy(id))return;followLoading.value.push(id);try{const{data:{user}}=await supabase.auth.getUser();if(!user)return;if(isFollowing(id)){const{error}=await supabase.from("follows").delete().eq("follower_id",user.id).eq("entrepreneur_id",id);if(error)throw error;followed.value=followed.value.filter(x=>x!==id);}else{const{error}=await supabase.from("follows").insert({follower_id:user.id,entrepreneur_id:id});if(error&&error.code!=="23505")throw error;if(!followed.value.includes(id))followed.value.push(id);}}catch(error){console.error(error);alert("No fue posible actualizar el seguimiento.");}finally{followLoading.value=followLoading.value.filter(x=>x!==id);}}
async function loadProductPreviews(){const{data,error}=await supabase.from("products").select(`id,entrepreneur_id,name,price,discount_percent,active,created_at,product_images(image_url,sort_order)`).eq("active",true).order("created_at",{ascending:false});if(error)throw error;const map={};for(const row of data||[]){if(!map[row.entrepreneur_id])map[row.entrepreneur_id]=[];if(map[row.entrepreneur_id].length>=3)continue;const images=(row.product_images||[]).slice().sort((a,b)=>a.sort_order-b.sort_order);map[row.entrepreneur_id].push({id:row.id,name:row.name,price:Number(row.price)||0,discountPercent:Number(row.discount_percent)||0,image:images[0]?.image_url||""});}return map;}
async function load(){loading.value=true;errorText.value="";try{const[{data,error},previews]=await Promise.all([supabase.rpc("get_entrepreneur_directory"),loadProductPreviews()]);if(error)throw error;businesses.value=(data||[]).map(row=>{const averageRating=Number(row.average_rating)||0,reviewCount=Number(row.review_count)||0;return{id:row.id,businessName:row.business_name,description:row.description||"",department:row.department||"",district:row.district||"",logoUrl:row.logo_url||"",payment:row.payment_methods||[],services:row.service_tags||[],tags:[...(row.payment_methods||[]),...(row.service_tags||[])],products:previews[row.id]||[],averageRating,reviewCount,featureScore:reviewCount?((averageRating*reviewCount)+(4*3))/(reviewCount+3):0};}).sort((a,b)=>a.businessName.localeCompare(b.businessName,"es"));await loadFollows();}catch(error){console.error(error);errorText.value="No pudimos cargar los emprendimientos.";}finally{loading.value=false;}}
onMounted(load);
</script>
<template>
<div class="min-h-screen bg-[#F8FBFC] pb-[78px] text-gray-700 lg:pb-10">
    <CustomerHeader v-model="search" v-model:department="department" active="entrepreneurs" search-placeholder="Buscar emprendimiento, producto, servicio o zona"/>
    <main class="mx-auto max-w-[1450px] px-3 py-5 sm:px-5 lg:px-8 lg:py-7">
        <div class="mb-6"><p class="text-xs font-black uppercase tracking-[.14em] text-[#00B4D8]">Comunidad Thrive</p><h1 class="mt-1 text-2xl font-black text-gray-800">Emprendedores</h1><p class="mt-1 text-sm text-gray-400">Descubre quién está detrás de cada producto.</p></div>
        <div v-if="loading" class="py-24 text-center"><div class="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-[#CAF0F8] border-t-[#00B4D8]"></div></div>
        <div v-else-if="errorText" class="bg-white p-10 text-center sm:rounded-[22px]"><p class="font-black">{{ errorText }}</p><button class="mt-4 rounded-xl bg-[#00B4D8] px-5 py-3 font-bold text-white" @click="load">Reintentar</button></div>
        <template v-else>
            <section v-if="featured.length" class="mb-8"><div class="mb-3 flex items-end justify-between"><div><p class="text-xs font-black uppercase tracking-[.12em] text-[#00B4D8]">Mejor valorados</p><h2 class="mt-1 text-xl font-black text-gray-700">Destacados</h2></div></div><div class="flex gap-3 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
                <article v-for="business in featured" :key="`featured-${business.id}`" class="w-[270px] shrink-0 cursor-pointer border-l-4 border-[#00B4D8] bg-white p-4 shadow-sm sm:rounded-r-[18px]" @click="open(business.id)"><div class="flex items-center gap-3"><img v-if="business.logoUrl" :src="business.logoUrl" class="h-14 w-14 shrink-0 rounded-full object-cover ring-2 ring-[#CAF0F8]"><div v-else class="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-[#EAF9FC] font-black text-[#0077B6]">{{ initials(business.businessName) }}</div><div class="min-w-0"><h3 class="truncate font-black text-gray-700">{{ business.businessName }}</h3><p class="mt-1 text-xs text-gray-400">{{ business.district||business.department }}</p><p class="mt-1 text-xs font-bold text-amber-500">★ {{ business.averageRating.toFixed(1) }} <span class="font-medium text-gray-400">· {{ business.reviewCount }} reseñas</span></p></div></div><div v-if="business.products.length" class="mt-3 flex gap-1.5"><button v-for="product in business.products" :key="product.id" type="button" class="relative h-12 w-12 overflow-hidden rounded-xl bg-gray-100" :title="product.name" @click.stop="openProduct(product.id)"><img v-if="product.image" :src="product.image" :alt="product.name" class="h-full w-full object-cover"><span v-else class="flex h-full w-full items-center justify-center text-[8px] font-bold text-gray-400">Sin foto</span><span v-if="product.discountPercent>0" class="absolute bottom-0 left-0 right-0 bg-rose-500 py-0.5 text-[7px] font-black text-white">-{{ Math.round(product.discountPercent) }}%</span></button></div></article>
            </div></section>
            <section v-if="!filtered.length" class="bg-white px-6 py-14 text-center sm:rounded-[22px]"><h3 class="font-black text-gray-700">No encontramos emprendimientos</h3><p class="mt-2 text-sm text-gray-400">Prueba otra búsqueda o un departamento diferente.</p></section>
            <section v-else class="grid gap-3 lg:grid-cols-2">
                <article v-for="business in filtered" :key="business.id" class="group bg-white p-4 sm:rounded-[20px] sm:border sm:border-gray-100">
                    <div class="flex items-start gap-4"><button type="button" class="shrink-0" @click="open(business.id)"><img v-if="business.logoUrl" :src="business.logoUrl" :alt="business.businessName" class="h-16 w-16 rounded-full object-cover ring-2 ring-[#CAF0F8]"><span v-else class="flex h-16 w-16 items-center justify-center rounded-full bg-[#EAF9FC] text-sm font-black text-[#0077B6]">{{ initials(business.businessName) }}</span></button><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><button type="button" class="min-w-0 text-left" @click="open(business.id)"><h2 class="truncate text-lg font-black text-gray-700">{{ business.businessName }}</h2><p class="mt-0.5 text-xs font-semibold text-gray-400">{{ business.district||business.department }}</p></button><button type="button" :disabled="busy(business.id)" class="shrink-0 rounded-full border px-3 py-1.5 text-[10px] font-bold" :class="isFollowing(business.id)?'border-[#90E0EF] bg-[#EAF9FC] text-[#0077B6]':'border-gray-200 text-gray-500'" @click="toggleFollow(business.id)">{{ isFollowing(business.id)?'Siguiendo':'Seguir +' }}</button></div><div class="mt-2 flex items-center gap-2 text-xs"><span class="font-black text-amber-500">★ {{ business.averageRating.toFixed(1) }}</span><span class="text-gray-400">{{ business.reviewCount }} reseñas</span></div></div></div>
                    <p class="mt-3 line-clamp-2 text-sm leading-6 text-gray-500">{{ business.description||"Conoce este emprendimiento y lo que ofrece dentro de Thrive." }}</p>
                    <div v-if="business.tags.length" class="mt-3 flex flex-wrap gap-1.5"><span v-for="tag in business.tags.slice(0,4)" :key="tag" class="rounded-full border px-2.5 py-1 text-[9px] font-bold" :class="tagClass(tag)">{{ tag }}</span></div>
                    <!-- La vista previa solo aparece cuando el emprendimiento ya publicó productos. -->
                    <div v-if="business.products.length" class="mt-4 border-t border-gray-100 pt-3"><div class="mb-2 flex items-center justify-between"><p class="text-[10px] font-black uppercase tracking-[.1em] text-gray-400">Una mirada a su catálogo</p><button type="button" class="text-[10px] font-bold text-[#0077B6]" @click="open(business.id)">Ver todos</button></div><div class="grid grid-cols-3 gap-2"><button v-for="product in business.products" :key="product.id" type="button" class="min-w-0 text-left" @click="openProduct(product.id)"><div class="relative overflow-hidden rounded-xl bg-gray-100"><img v-if="product.image" :src="product.image" :alt="product.name" class="aspect-square w-full object-cover"><div v-else class="flex aspect-square items-center justify-center text-[9px] text-gray-400">Sin foto</div><span v-if="product.discountPercent>0" class="absolute left-1.5 top-1.5 rounded-full bg-rose-500 px-1.5 py-0.5 text-[8px] font-black text-white">-{{ Math.round(product.discountPercent) }}%</span></div><p class="mt-1 truncate text-[10px] font-bold text-gray-600">{{ product.name }}</p><div class="flex items-baseline gap-1"><span v-if="product.discountPercent>0" class="text-[8px] text-gray-400 line-through">{{ money(product.price) }}</span><span class="text-[10px] font-black" :class="product.discountPercent>0?'text-rose-600':'text-[#4F7180]'">{{ money(product.discountPercent>0?salePrice(product):product.price) }}</span></div></button></div></div>
                    <button v-else type="button" class="mt-4 flex w-full items-center justify-between border-t border-gray-100 pt-3 text-xs font-bold text-[#0077B6]" @click="open(business.id)"><span>Ver perfil</span><span class="transition group-hover:translate-x-1">→</span></button>
                </article>
            </section>
        </template>
    </main>
</div>
</template>
