<script setup>
import { ref, computed, onMounted } from "vue";
import { useRouter } from "vue-router";
import { supabase } from "../lib/supabaseClient";
import CustomerNav from "../components/customer/CustomerNav.vue";
const router = useRouter();
const businesses = ref([]); const loading = ref(true); const errorText = ref("");
const search = ref(""); const department = ref("Todos"); const followed = ref([]); const followLoading = ref([]);
const departments = ["Todos","Ahuachapán","Cabañas","Chalatenango","Cuscatlán","La Libertad","La Paz","La Unión","Morazán","San Miguel","San Salvador","San Vicente","Santa Ana","Sonsonate","Usulután"];
const filtered = computed(() => { const q=search.value.toLowerCase().trim(); return businesses.value.filter(b => (department.value==="Todos"||b.department===department.value) && (!q||[b.businessName,b.description,b.department,b.district,...b.tags].join(" ").toLowerCase().includes(q))); });
// Se suaviza el promedio para que una sola reseña de 5 no desplace a negocios con más historial.
const featured = computed(() => businesses.value.filter(b=>b.reviewCount>0).slice().sort((a,b)=>b.featureScore-a.featureScore||b.reviewCount-a.reviewCount).slice(0,6));
function initials(name){return String(name||"TH").trim().split(/\s+/).slice(0,2).map(w=>w[0]?.toUpperCase()).join("");}
function open(id){router.push({name:"Business",params:{id}});}
function isFollowing(id){return followed.value.includes(id);} function busy(id){return followLoading.value.includes(id);}
async function loadFollows(){const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const {data}=await supabase.from("follows").select("entrepreneur_id").eq("follower_id",user.id); followed.value=(data||[]).map(r=>r.entrepreneur_id);}
async function toggleFollow(id){if(busy(id))return; followLoading.value.push(id); try{const {data:{user}}=await supabase.auth.getUser(); if(!user)return; if(isFollowing(id)){const {error}=await supabase.from("follows").delete().eq("follower_id",user.id).eq("entrepreneur_id",id);if(error)throw error;followed.value=followed.value.filter(x=>x!==id);}else{const {error}=await supabase.from("follows").insert({follower_id:user.id,entrepreneur_id:id});if(error&&error.code!=="23505")throw error;if(!followed.value.includes(id))followed.value.push(id);}}catch(e){console.error(e);alert("No fue posible actualizar el seguimiento.");}finally{followLoading.value=followLoading.value.filter(x=>x!==id);}}
async function load(){loading.value=true;errorText.value="";try{const {data,error}=await supabase.rpc("get_entrepreneur_directory");if(error)throw error;businesses.value=(data||[]).map(r=>{const avg=Number(r.average_rating)||0;const count=Number(r.review_count)||0;return{id:r.id,businessName:r.business_name,description:r.description||"",department:r.department||"",district:r.district||"",logoUrl:r.logo_url||"",payment:r.payment_methods||[],services:r.service_tags||[],tags:[...(r.payment_methods||[]),...(r.service_tags||[])],averageRating:avg,reviewCount:count,featureScore:count?((avg*count)+(4*3))/(count+3):0};}).sort((a,b)=>a.businessName.localeCompare(b.businessName,"es"));await loadFollows();}catch(e){console.error(e);errorText.value="No pudimos cargar los emprendimientos.";}finally{loading.value=false;}}
onMounted(load);
</script>
<template>
<div class="min-h-screen bg-[#F8FBFC] pb-[78px] text-gray-700 lg:pb-10">
    <header class="sticky top-0 z-40 bg-[#F8FBFC]/95 backdrop-blur-xl"><div class="mx-auto max-w-[1450px] px-3 py-4 sm:px-5 lg:px-8"><div class="rounded-[28px] bg-gradient-to-r from-[#0077B6] to-[#00B4D8] p-5 text-white shadow-[0_14px_40px_rgba(0,119,182,.18)] sm:p-7"><p class="text-xs font-black uppercase tracking-[.18em] text-white/70">Directorio Thrive</p><div class="mt-2 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 class="text-3xl font-black sm:text-4xl">Encuentra emprendimientos</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-white/75">Descubre negocios de todo El Salvador, consulta su reputación y entra directamente a su perfil.</p></div><div class="w-full rounded-[18px] bg-white/15 px-4 py-3 backdrop-blur lg:max-w-md"><input v-model="search" type="search" placeholder="Buscar por nombre, categoría o zona" class="w-full bg-transparent text-sm font-semibold text-white outline-none placeholder:text-white/55"></div></div></div><div class="mt-3"><CustomerNav active="entrepreneurs" /></div><div class="mt-3 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><button v-for="item in departments" :key="item" class="whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold" :class="department===item?'bg-[#0077B6] text-white':'bg-white text-[#0077B6] ring-1 ring-[#CAF0F8]'" @click="department=item">{{ item }}</button></div></div></header>
    <main class="mx-auto max-w-[1450px] px-3 py-6 sm:px-5 lg:px-8">
        <div v-if="loading" class="py-24 text-center"><div class="mx-auto h-9 w-9 animate-spin rounded-full border-4 border-[#CAF0F8] border-t-[#00B4D8]"></div></div>
        <div v-else-if="errorText" class="rounded-[24px] bg-white p-10 text-center shadow-sm"><p class="font-black">{{ errorText }}</p><button class="mt-4 rounded-xl bg-[#00B4D8] px-5 py-3 font-bold text-white" @click="load">Reintentar</button></div>
        <template v-else>
            <section class="mb-9"><div class="mb-4"><p class="text-xs font-black uppercase tracking-[.15em] text-[#00B4D8]">Mejor valorados</p><h2 class="mt-1 text-2xl font-black">Emprendedores destacados</h2></div><div v-if="featured.length" class="flex gap-4 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><article v-for="b in featured" :key="`f-${b.id}`" class="w-[285px] shrink-0 cursor-pointer rounded-[26px] bg-white p-5 shadow-sm ring-1 ring-[#CAF0F8]" @click="open(b.id)"><div class="flex items-start justify-between"><img v-if="b.logoUrl" :src="b.logoUrl" class="h-16 w-16 rounded-[20px] object-cover ring-4 ring-[#EAF9FC]"><div v-else class="flex h-16 w-16 items-center justify-center rounded-[20px] bg-[#EAF9FC] font-black text-[#0077B6]">{{ initials(b.businessName) }}</div><span class="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-600">★ {{ b.averageRating.toFixed(1) }}</span></div><h3 class="mt-4 text-xl font-black text-gray-800">{{ b.businessName }}</h3><p class="mt-1 text-xs font-semibold text-gray-400">{{ b.district || b.department }} · {{ b.reviewCount }} reseñas</p><div class="mt-3 flex flex-wrap gap-1.5"><span v-for="tag in b.tags.slice(0,3)" :key="tag" class="rounded-full bg-[#EAF9FC] px-2.5 py-1 text-[10px] font-bold text-[#0077B6]">{{ tag }}</span></div></article></div><div v-else class="rounded-[22px] border border-dashed border-[#90E0EF] bg-[#EAF9FC]/50 p-6 text-sm text-gray-500">Los destacados aparecerán automáticamente cuando los clientes comiencen a calificar emprendimientos.</div></section>
            <section><div class="mb-4 flex items-end justify-between"><div><p class="text-xs font-black uppercase tracking-[.15em] text-[#00B4D8]">Comunidad</p><h2 class="mt-1 text-2xl font-black">Todos los emprendimientos</h2></div><p class="text-sm font-semibold text-gray-400">{{ filtered.length }}</p></div><div v-if="!filtered.length" class="rounded-[24px] bg-white p-12 text-center shadow-sm">No encontramos emprendimientos con esos filtros.</div><div v-else class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article v-for="b in filtered" :key="b.id" class="group cursor-pointer rounded-[26px] bg-white p-5 shadow-sm ring-1 ring-gray-100 transition hover:-translate-y-0.5 hover:shadow-md" @click="open(b.id)"><div class="flex gap-4"><img v-if="b.logoUrl" :src="b.logoUrl" class="h-20 w-20 shrink-0 rounded-[22px] object-cover ring-1 ring-[#CAF0F8]"><div v-else class="flex h-20 w-20 shrink-0 items-center justify-center rounded-[22px] bg-[#EAF9FC] font-black text-[#0077B6]">{{ initials(b.businessName) }}</div><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><h3 class="truncate text-lg font-black text-gray-800">{{ b.businessName }}</h3><button type="button" :disabled="busy(b.id)" class="shrink-0 rounded-full px-3 py-1.5 text-[10px] font-black" :class="isFollowing(b.id)?'bg-[#CAF0F8] text-[#0077B6]':'bg-gray-50 text-gray-500'" @click.stop="toggleFollow(b.id)">{{ isFollowing(b.id)?'Siguiendo':'Seguir +' }}</button></div><p class="mt-1 text-xs font-semibold text-gray-400">{{ b.district || b.department }}</p><div class="mt-2 flex items-center gap-2 text-xs"><span class="font-black text-amber-500">★ {{ b.averageRating.toFixed(1) }}</span><span class="text-gray-400">{{ b.reviewCount }} reseñas</span></div></div></div><p class="mt-4 line-clamp-2 text-sm leading-6 text-gray-500">{{ b.description || 'Conoce este emprendimiento y sus productos en Thrive.' }}</p><div class="mt-4 flex flex-wrap gap-1.5"><span v-for="tag in b.tags.slice(0,4)" :key="tag" class="rounded-full bg-[#EAF9FC] px-2.5 py-1 text-[10px] font-bold text-[#0077B6]">{{ tag }}</span></div><div class="mt-4 flex items-center justify-between border-t border-gray-100 pt-4 text-xs font-black text-[#0077B6]"><span>Ver emprendimiento</span><span>→</span></div></article></div></section>
        </template>
    </main>
</div>
</template>
